Add security configuration based on Basic authentication.
dmkofgl/NewsPortal pull request #12
Opened 2019-03-04 15:12 UTC by dmkofgl

2019-03-07 09:50 UTC, avinahradau commented on src/main/java/dl/news/portal/web/controller/UserController.java
> +@RequestMapping(value = "/users",produces =MediaType.APPLICATION_JSON_VALUE )
refactor formatting here

2019-03-07 11:00 UTC, dmkofgl commented on src/main/java/dl/news/portal/web/controller/UserController.java
> +@RequestMapping(value = "/users",produces =MediaType.APPLICATION_JSON_VALUE )
Done

2019-03-13 08:44 UTC, avinahradau requested changes

2019-03-13 08:44 UTC, avinahradau commented on src/main/java/dl/news/portal/domain/service/impl/UserDetailService.java
> +    private UserDetails mapUser(User user) {
unlear name map User with what?

2019-03-13 08:44 UTC, avinahradau commented on src/main/java/dl/news/portal/web/config/security/BasicAuthenticationConfig.java
> +        return new BCryptPasswordEncoder(5);
What does this magic digit mean?

2019-03-13 15:34 UTC, dmkofgl commented on src/main/java/dl/news/portal/domain/service/impl/UserDetailService.java
> +    private UserDetails mapUser(User user) {
Map to UserDetails

2019-03-13 15:34 UTC, dmkofgl commented on src/main/java/dl/news/portal/web/config/security/BasicAuthenticationConfig.java
> +        return new BCryptPasswordEncoder(5);
It's bcript password encoder strength

2019-03-18 09:38 UTC, avinahradau approved these changes

2019-03-18 09:57 UTC, merged